name: 'New Release action'
description: 'Create a release on GitHub'
author: 'Théo Gillet - theocode-33'
icon: bookmark
color: green
inputs:
  version:
    description: 'The version of the release'
    required: true
  token:
    description: 'The GitHub token'
    required: true

runs:
  using: node16
  main: dist/index.js
